spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=teamsync
server.port=8080
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.profiles.default=local

spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
app.frontend-url=${FRONTEND_URL:}

supabase.url=${SUPABASE_URL:}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:}
supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET:}